package Day13;

public class Testng1 {

	public static void main(String[] args) {
		
		// TESTNG FRAMEWORK 
		
		// FRAME WORK : MAKING UR WORK EASY AND TO SPEED UP THE COMPLETION
		
		// TESTNG FRAMEWORK ; TESTING WORK WHIC MAKES UR TESTING EASIER 
		
		// WHICH GENERATES REPORTS AUTOMATICALLY 
		
		// GIVES CLEAR EXPLANATION ON WHAT IS GETTING FAILED AND PASSED 
		
		// EXECUTION WILL HAPPEN IN MAIN METHOD 
		
		//  TESTNG EVERYTHING IS REPRESENTATED IN TAGS/ANNOTATIONS 
		
		// @ [SYMBOL]
		
		// TESTNG WE CAN USE N NO OF MAIN METHODS 
		
		// MAIN METHOD ARE DEFINED AS @TEST 
		
		// TEST NG 
		
		// WE NEED TO INSTALL THE PLUGIN TEST NG 
		
		// WE NEED TO MENTION THE DEPENDENCY IN POM.XML
		
		
		
		

	}



}
